### Particle Image Function
### Version: 1.0.4
### Width: 32
### Height: 32
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0 ^-0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.1 ^-0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.3 ^-0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.4 ^-0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.4 ^-0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.5 ^-0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.6 ^-0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.6 ^-0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.7 ^-0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.8 ^-0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.7 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.8 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.9 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^0.9 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.1 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.1 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.2 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.2 ^-0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.3 ^-0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.4 ^-0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.3 ^-0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.4 ^-0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.5 ^-0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.5 ^-1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.6 ^-1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.7 ^-1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.6 ^-1.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.7 ^-1.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.8 ^-1.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.7 ^-1.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.8 ^-1.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.9 ^-1.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.8 ^-1.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.9 ^-1.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2 ^-1.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^1.9 ^-1.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2 ^-1.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.1 ^-1.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.2 ^-1.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2 ^-1.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.1 ^-1.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.2 ^-1.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.2 ^-1.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.3 ^-1.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.4 ^-1.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.2 ^-1.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.3 ^-1.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.4 ^-1.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.4 ^-1.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.5 ^-1.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.6 ^-1.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.4 ^-1.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.5 ^-1.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.6 ^-1.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.6 ^-2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.7 ^-2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.6 ^-2.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.7 ^-2.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.8 ^-2.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.7 ^-2.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.8 ^-2.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.9 ^-2.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.8 ^-2.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.9 ^-2.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.9 ^-2.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^3 ^-2.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^2.9 ^-2.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^3 ^-2.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^3 ^-2.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^3.1 ^-2.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^3 ^-2.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^3.1 ^-2.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^3.1 ^-2.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^3.1 ^-2.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.000,0.000],scale:0.75} ^3.1 ^-3 ^0 0 0 0 0 1 force @a
