### Particle Image Function
### Version: 1.0.4
### Width: 20
### Height: 20
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle dust{color:[0.000,0.200,0.188],scale:0.5} ^0.375 ^0 ^-0.375 0 0 0 0 1 force @a
particle dust{color:[0.341,0.863,0.851],scale:0.5} ^0.25 ^0 ^-0.5 0 0 0 0 1 force @a
particle dust{color:[0.220,0.620,0.620],scale:0.5} ^0.25 ^0 ^-0.375 0 0 0 0 1 force @a
particle dust{color:[0.027,0.992,0.992],scale:0.5} ^0.125 ^0 ^-0.5 0 0 0 0 1 force @a
particle dust{color:[0.780,0.933,0.922],scale:0.5} ^0.125 ^0 ^-0.375 0 0 0 0 1 force @a
particle dust{color:[0.420,1.000,1.000],scale:0.5} ^0.125 ^0 ^-0.25 0 0 0 0 1 force @a
particle dust{color:[0.471,0.980,0.980],scale:0.5} ^0.125 ^0 ^-0.125 0 0 0 0 1 force @a
particle dust{color:[0.451,0.992,0.980],scale:0.5} ^0.125 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.400,0.890,0.882],scale:0.5} ^0.125 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[0.439,0.953,0.953],scale:0.5} ^0.125 ^0 ^0.25 0 0 0 0 1 force @a
particle dust{color:[0.439,0.953,0.953],scale:0.5} ^0.125 ^0 ^0.375 0 0 0 0 1 force @a
particle dust{color:[0.490,0.973,0.961],scale:0.5} ^0.125 ^0 ^0.5 0 0 0 0 1 force @a
particle dust{color:[0.451,0.992,0.992],scale:0.5} ^0.125 ^0 ^0.625 0 0 0 0 1 force @a
particle dust{color:[0.431,0.902,0.902],scale:0.5} ^0.125 ^0 ^0.75 0 0 0 0 1 force @a
particle dust{color:[0.451,0.980,0.980],scale:0.5} ^0.125 ^0 ^0.875 0 0 0 0 1 force @a
particle dust{color:[0.420,1.000,1.000],scale:0.5} ^0.125 ^0 ^1 0 0 0 0 1 force @a
particle dust{color:[0.000,0.478,0.478],scale:0.5} ^0 ^0 ^-1.125 0 0 0 0 1 force @a
particle dust{color:[0.408,0.831,0.831],scale:0.5} ^0 ^0 ^-1 0 0 0 0 1 force @a
particle dust{color:[0.208,0.910,0.910],scale:0.5} ^0 ^0 ^-0.875 0 0 0 0 1 force @a
particle dust{color:[0.310,0.871,0.871],scale:0.5} ^0 ^0 ^-0.75 0 0 0 0 1 force @a
particle dust{color:[0.000,0.490,0.478],scale:0.5} ^0 ^0 ^-0.625 0 0 0 0 1 force @a
particle dust{color:[0.361,0.910,0.882],scale:0.5} ^0 ^0 ^-0.5 0 0 0 0 1 force @a
particle dust{color:[0.251,0.820,0.812],scale:0.5} ^0 ^0 ^-0.375 0 0 0 0 1 force @a
particle dust{color:[0.118,0.761,0.710],scale:0.5} ^0 ^0 ^-0.25 0 0 0 0 1 force @a
particle dust{color:[0.118,0.761,0.710],scale:0.5} ^0 ^0 ^-0.125 0 0 0 0 1 force @a
particle dust{color:[0.129,0.773,0.722],scale:0.5} ^0 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.118,0.761,0.710],scale:0.5} ^0 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[0.118,0.773,0.710],scale:0.5} ^0 ^0 ^0.25 0 0 0 0 1 force @a
particle dust{color:[0.129,0.780,0.722],scale:0.5} ^0 ^0 ^0.375 0 0 0 0 1 force @a
particle dust{color:[0.110,0.761,0.710],scale:0.5} ^0 ^0 ^0.5 0 0 0 0 1 force @a
particle dust{color:[0.129,0.761,0.710],scale:0.5} ^0 ^0 ^0.625 0 0 0 0 1 force @a
particle dust{color:[0.118,0.761,0.710],scale:0.5} ^0 ^0 ^0.75 0 0 0 0 1 force @a
particle dust{color:[0.137,0.780,0.722],scale:0.5} ^0 ^0 ^0.875 0 0 0 0 1 force @a
particle dust{color:[0.369,0.992,0.953],scale:0.5} ^0 ^0 ^1 0 0 0 0 1 force @a
particle dust{color:[0.420,1.000,1.000],scale:0.5} ^0 ^0 ^1.125 0 0 0 0 1 force @a
particle dust{color:[0.020,1.000,0.992],scale:0.5} ^-0.125 ^0 ^-0.5 0 0 0 0 1 force @a
particle dust{color:[0.753,0.910,0.890],scale:0.5} ^-0.125 ^0 ^-0.375 0 0 0 0 1 force @a
particle dust{color:[0.431,1.000,0.992],scale:0.5} ^-0.125 ^0 ^-0.25 0 0 0 0 1 force @a
particle dust{color:[0.439,1.000,1.000],scale:0.5} ^-0.125 ^0 ^-0.125 0 0 0 0 1 force @a
particle dust{color:[0.431,1.000,1.000],scale:0.5} ^-0.125 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.451,1.000,1.000],scale:0.5} ^-0.125 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[0.431,1.000,0.992],scale:0.5} ^-0.125 ^0 ^0.25 0 0 0 0 1 force @a
particle dust{color:[0.459,1.000,1.000],scale:0.5} ^-0.125 ^0 ^0.375 0 0 0 0 1 force @a
particle dust{color:[0.451,0.992,0.992],scale:0.5} ^-0.125 ^0 ^0.5 0 0 0 0 1 force @a
particle dust{color:[0.451,1.000,1.000],scale:0.5} ^-0.125 ^0 ^0.625 0 0 0 0 1 force @a
particle dust{color:[0.471,1.000,1.000],scale:0.5} ^-0.125 ^0 ^0.75 0 0 0 0 1 force @a
particle dust{color:[0.471,1.000,0.992],scale:0.5} ^-0.125 ^0 ^0.875 0 0 0 0 1 force @a
particle dust{color:[0.420,1.000,1.000],scale:0.5} ^-0.125 ^0 ^1 0 0 0 0 1 force @a
particle dust{color:[0.329,0.722,0.729],scale:0.5} ^-0.25 ^0 ^-0.5 0 0 0 0 1 force @a
particle dust{color:[0.149,0.329,0.318],scale:0.5} ^-0.25 ^0 ^-0.375 0 0 0 0 1 force @a
particle dust{color:[0.008,0.478,0.471],scale:0.5} ^-0.375 ^0 ^-0.375 0 0 0 0 1 force @a

execute as @e[distance=..2,limit=1,sort=nearest,type=!#kits:non_entity,tag=!Invincible,tag=!Vergil,tag=!InLabyrinth] at @s run function kits:char/vergil/summonedsworddamage
execute if entity @s[tag=!summonedswordsdelay] if entity @e[type=area_effect_cloud,tag=summonedswordsdestination,distance=..3.1] run playsound minecraft:entity.drowned.shoot neutral @a[distance=..30] ~ ~ ~ 3 2 1
execute if entity @s[tag=!summonedswordsdelay] if entity @e[type=area_effect_cloud,tag=summonedswordsdestination,distance=..3.1] run kill @s 
