### Particle Image Function
### Version: 1.0.4
### Width: 8
### Height: 8
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.09375 ^0.28125 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0 ^0.28125 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.09375 ^0.28125 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.1875 ^0.28125 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.28125 ^0.28125 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.28125 ^0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.1875 ^0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.09375 ^0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0 ^0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.09375 ^0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.1875 ^0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.28125 ^0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.28125 ^0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.1875 ^0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.09375 ^0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0 ^0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.09375 ^0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.1875 ^0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.28125 ^0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.28125 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.1875 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.09375 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.09375 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.1875 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.28125 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.28125 ^-0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.1875 ^-0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.09375 ^-0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0 ^-0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.09375 ^-0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.1875 ^-0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.28125 ^-0.09375 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.28125 ^-0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.1875 ^-0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.09375 ^-0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0 ^-0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.09375 ^-0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.1875 ^-0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.28125 ^-0.1875 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.09375 ^-0.28125 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.1875 ^-0.28125 ^0 0 0 0 0 1 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.28125 ^-0.28125 ^0 0 0 0 0 1 force @a
