### Particle Image Function
### Version: 1.0.4
### Width: 32
### Height: 32
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter
scoreboard players remove @p[tag=Kirito] kits.timer 1
particle dust{color:[0.200,0.549,0.690],scale:0.75} ^0 ^-0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[0.059,0.388,0.510],scale:0.75} ^0.1 ^-0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[0.408,0.780,0.953],scale:0.75} ^0.3 ^-0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[0.251,0.541,0.690],scale:0.75} ^0.4 ^-0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[0.157,0.561,0.702],scale:0.75} ^0.4 ^-0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[0.682,0.890,0.980],scale:0.75} ^0.5 ^-0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[0.388,0.631,0.741],scale:0.75} ^0.6 ^-0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[0.451,0.780,0.953],scale:0.75} ^0.6 ^-0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[0.800,0.910,0.953],scale:0.75} ^0.7 ^-0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[0.251,0.510,0.651],scale:0.75} ^0.8 ^-0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[0.169,0.459,0.561],scale:0.75} ^0.7 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[0.761,0.871,0.910],scale:0.75} ^0.8 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[0.451,0.792,0.933],scale:0.75} ^0.9 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[0.290,0.580,0.671],scale:0.75} ^0.9 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[0.800,0.933,0.961],scale:0.75} ^1 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[0.188,0.549,0.682],scale:0.75} ^1.1 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[0.157,0.451,0.580],scale:0.75} ^1 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[0.831,0.902,0.933],scale:0.75} ^1.1 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[0.502,0.812,0.933],scale:0.75} ^1.2 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[0.439,0.780,0.953],scale:0.75} ^1.2 ^-0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[0.863,0.902,0.933],scale:0.75} ^1.3 ^-0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[0.408,0.561,0.682],scale:0.75} ^1.4 ^-0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[0.200,0.549,0.671],scale:0.75} ^1.3 ^-0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[0.922,1.000,1.000],scale:0.75} ^1.4 ^-0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[0.420,0.639,0.710],scale:0.75} ^1.5 ^-0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[0.620,0.871,0.941],scale:0.75} ^1.5 ^-1 ^0 0 0 0 0 1 force @a
particle dust{color:[0.812,0.890,0.933],scale:0.75} ^1.6 ^-1 ^0 0 0 0 0 1 force @a
particle dust{color:[0.200,0.541,0.659],scale:0.75} ^1.7 ^-1 ^0 0 0 0 0 1 force @a
particle dust{color:[0.561,0.722,0.812],scale:0.75} ^1.6 ^-1.1 ^0 0 0 0 0 1 force @a
particle dust{color:[0.992,0.992,1.000],scale:0.75} ^1.7 ^-1.1 ^0 0 0 0 0 1 force @a
particle dust{color:[0.420,0.631,0.710],scale:0.75} ^1.8 ^-1.1 ^0 0 0 0 0 1 force @a
particle dust{color:[0.451,0.800,0.910],scale:0.75} ^1.7 ^-1.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,1.000,0.980],scale:0.75} ^1.8 ^-1.2 ^0 0 0 0 0 1 force @a
particle dust{color:[0.349,0.561,0.710],scale:0.75} ^1.9 ^-1.2 ^0 0 0 0 0 1 force @a
particle dust{color:[0.639,0.753,0.792],scale:0.75} ^1.8 ^-1.3 ^0 0 0 0 0 1 force @a
particle dust{color:[0.800,0.941,0.961],scale:0.75} ^1.9 ^-1.3 ^0 0 0 0 0 1 force @a
particle dust{color:[0.459,0.780,0.902],scale:0.75} ^2 ^-1.3 ^0 0 0 0 0 1 force @a
particle dust{color:[0.251,0.592,0.800],scale:0.75} ^1.9 ^-1.4 ^0 0 0 0 0 1 force @a
particle dust{color:[0.992,1.000,0.992],scale:0.75} ^2 ^-1.4 ^0 0 0 0 0 1 force @a
particle dust{color:[0.780,0.910,0.941],scale:0.75} ^2.1 ^-1.4 ^0 0 0 0 0 1 force @a
particle dust{color:[0.188,0.439,0.561],scale:0.75} ^2.2 ^-1.4 ^0 0 0 0 0 1 force @a
particle dust{color:[0.200,0.549,0.710],scale:0.75} ^2 ^-1.5 ^0 0 0 0 0 1 force @a
particle dust{color:[0.910,0.973,0.992],scale:0.75} ^2.1 ^-1.5 ^0 0 0 0 0 1 force @a
particle dust{color:[0.992,1.000,1.000],scale:0.75} ^2.2 ^-1.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,1.000,1.000],scale:0.75} ^2.2 ^-1.6 ^0 0 0 0 0 1 force @a
particle dust{color:[0.863,0.933,0.961],scale:0.75} ^2.3 ^-1.6 ^0 0 0 0 0 1 force @a
particle dust{color:[0.208,0.529,0.651],scale:0.75} ^2.4 ^-1.6 ^0 0 0 0 0 1 force @a
particle dust{color:[0.149,0.310,0.361],scale:0.75} ^2.2 ^-1.7 ^0 0 0 0 0 1 force @a
particle dust{color:[0.843,0.933,0.973],scale:0.75} ^2.3 ^-1.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.992,1.000],scale:0.75} ^2.4 ^-1.7 ^0 0 0 0 0 1 force @a
particle dust{color:[0.980,1.000,1.000],scale:0.75} ^2.4 ^-1.8 ^0 0 0 0 0 1 force @a
particle dust{color:[0.922,0.973,0.992],scale:0.75} ^2.5 ^-1.8 ^0 0 0 0 0 1 force @a
particle dust{color:[0.208,0.541,0.651],scale:0.75} ^2.6 ^-1.8 ^0 0 0 0 0 1 force @a
particle dust{color:[0.180,0.310,0.380],scale:0.75} ^2.4 ^-1.9 ^0 0 0 0 0 1 force @a
particle dust{color:[0.843,0.933,0.961],scale:0.75} ^2.5 ^-1.9 ^0 0 0 0 0 1 force @a
particle dust{color:[0.961,1.000,1.000],scale:0.75} ^2.6 ^-1.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,1.000,1.000],scale:0.75} ^2.6 ^-2 ^0 0 0 0 0 1 force @a
particle dust{color:[0.820,0.922,0.992],scale:0.75} ^2.7 ^-2 ^0 0 0 0 0 1 force @a
particle dust{color:[0.220,0.451,0.580],scale:0.75} ^2.6 ^-2.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,1.000,1.000],scale:0.75} ^2.7 ^-2.1 ^0 0 0 0 0 1 force @a
particle dust{color:[0.439,0.800,0.933],scale:0.75} ^2.8 ^-2.1 ^0 0 0 0 0 1 force @a
particle dust{color:[0.200,0.290,0.318],scale:0.75} ^2.7 ^-2.2 ^0 0 0 0 0 1 force @a
particle dust{color:[0.992,1.000,0.992],scale:0.75} ^2.8 ^-2.2 ^0 0 0 0 0 1 force @a
particle dust{color:[0.188,0.549,0.682],scale:0.75} ^2.9 ^-2.2 ^0 0 0 0 0 1 force @a
particle dust{color:[0.812,0.890,0.953],scale:0.75} ^2.8 ^-2.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.992,1.000],scale:0.75} ^2.9 ^-2.3 ^0 0 0 0 0 1 force @a
particle dust{color:[0.992,1.000,1.000],scale:0.75} ^2.9 ^-2.4 ^0 0 0 0 0 1 force @a
particle dust{color:[0.271,0.620,0.773],scale:0.75} ^3 ^-2.4 ^0 0 0 0 0 1 force @a
particle dust{color:[0.639,0.741,0.800],scale:0.75} ^2.9 ^-2.5 ^0 0 0 0 0 1 force @a
particle dust{color:[0.992,1.000,1.000],scale:0.75} ^3 ^-2.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,1.000,1.000],scale:0.75} ^3 ^-2.6 ^0 0 0 0 0 1 force @a
particle dust{color:[0.208,0.451,0.549],scale:0.75} ^3.1 ^-2.6 ^0 0 0 0 0 1 force @a
particle dust{color:[0.851,0.933,0.953],scale:0.75} ^3 ^-2.7 ^0 0 0 0 0 1 force @a
particle dust{color:[0.569,0.800,0.882],scale:0.75} ^3.1 ^-2.7 ^0 0 0 0 0 1 force @a
particle dust{color:[0.761,0.933,1.000],scale:0.75} ^3.1 ^-2.8 ^0 0 0 0 0 1 force @a
particle dust{color:[0.851,0.902,0.941],scale:0.75} ^3.1 ^-2.9 ^0 0 0 0 0 1 force @a
particle dust{color:[0.290,0.439,0.522],scale:0.75} ^3.1 ^-3 ^0 0 0 0 0 1 force @a
