### Particle Image Function
### Version: 1.0.4
### Width: 14
### Height: 14
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^0.8571429 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^0.7142857 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.2857143 ^0.5714286 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.1428571 ^0.5714286 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^0.5714286 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.1428571 ^0.5714286 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.2857143 ^0.5714286 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.4285714 ^0.4285714 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.4285714 ^0.4285714 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.5714286 ^0.2857143 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.1428571 ^0.2857143 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^0.2857143 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.1428571 ^0.2857143 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.5714286 ^0.2857143 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.5714286 ^0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.2857143 ^0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.1428571 ^0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.1428571 ^0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.2857143 ^0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.5714286 ^0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.8571429 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.7142857 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.5714286 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.2857143 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.1428571 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.1428571 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.2857143 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.5714286 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.7142857 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.8571429 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.5714286 ^-0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.2857143 ^-0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.1428571 ^-0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^-0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.1428571 ^-0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.2857143 ^-0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.5714286 ^-0.1428571 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.5714286 ^-0.2857143 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.1428571 ^-0.2857143 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^-0.2857143 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.1428571 ^-0.2857143 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.5714286 ^-0.2857143 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.4285714 ^-0.4285714 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.4285714 ^-0.4285714 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.2857143 ^-0.5714286 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^-0.1428571 ^-0.5714286 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^-0.5714286 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.1428571 ^-0.5714286 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0.2857143 ^-0.5714286 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^-0.7142857 ^0 0 0 0 0 1 force @a
particle dust{color:[0.000,1.000,1.000],scale:0.75} ^0 ^-0.8571429 ^0 0 0 0 0 1 force @a


tp @s ~ ~ ~ facing entity @p[tag=Noctis]
