### Particle Image Function
### Version: 1.0.4
### Width: 12
### Height: 12
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.2083333 ^0 ^-0.0833333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.2083333 ^0 ^-0.0416667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.2083333 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.1666667 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.1666667 ^0 ^0.0416667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.1666667 ^0 ^0.0833333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.1666667 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.125 ^0 ^0.0833333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.125 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.125 ^0 ^0.1666667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.0833333 ^0 ^0.0833333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.0833333 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.0833333 ^0 ^0.1666667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.0833333 ^0 ^0.2083333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.0416667 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.0416667 ^0 ^0.1666667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0.0416667 ^0 ^0.2083333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0 ^0 ^0.1666667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^0 ^0 ^0.2083333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.0416667 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.0416667 ^0 ^0.1666667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.0416667 ^0 ^0.2083333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.0833333 ^0 ^0.0833333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.0833333 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.0833333 ^0 ^0.1666667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.0833333 ^0 ^0.2083333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.125 ^0 ^0.0416667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.125 ^0 ^0.0833333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.125 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.125 ^0 ^0.1666667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.1666667 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.1666667 ^0 ^0.0416667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.1666667 ^0 ^0.0833333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.1666667 ^0 ^0.125 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.2083333 ^0 ^-0.0833333 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.2083333 ^0 ^-0.0416667 0 0 0 0 1 force @a
particle dust{color:[1.500,0.000,0.000],scale:0.75} ^-0.2083333 ^0 ^0 0 0 0 0 1 force @a
