### Particle Image Function
### Version: 1.0.4
### Width: 7
### Height: 7
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.2142857 ^0.3571429 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.0714286 ^0.3571429 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.0714286 ^0.3571429 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.2142857 ^0.3571429 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.2142857 ^0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.0714286 ^0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.0714286 ^0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.2142857 ^0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.3571429 ^0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.5 ^0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.3571429 ^0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.2142857 ^0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.0714286 ^0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.0714286 ^0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.2142857 ^0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.3571429 ^0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.3571429 ^-0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.2142857 ^-0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.0714286 ^-0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.0714286 ^-0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.2142857 ^-0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.3571429 ^-0.0714286 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.3571429 ^-0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.2142857 ^-0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.0714286 ^-0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.0714286 ^-0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.2142857 ^-0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.3571429 ^-0.2142857 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^-0.0714286 ^-0.3571429 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.0714286 ^-0.3571429 ^0 0.1 0.1 0.1 0 5 force @a
particle dust{color:[0.773,0.600,0.400],scale:0.5} ^0.2142857 ^-0.3571429 ^0 0.1 0.1 0.1 0 5 force @a
