### Particle Image Function
### Version: 1.0.4
### Width: 20
### Height: 20
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.7 ^1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.8 ^1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.9 ^1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.7 ^0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.8 ^0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.9 ^0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.5 ^0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.6 ^0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.9 ^0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.4 ^0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.9 ^0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.3 ^0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.8 ^0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.2 ^0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.7 ^0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.2 ^0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.7 ^0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0 ^0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.1 ^0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.5 ^0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.6 ^0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.7 ^0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.6 ^0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.1 ^0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.4 ^0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.7 ^0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.5 ^0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.4 ^0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.2 ^0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.3 ^0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.6 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.3 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.2 ^0 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.6 ^-0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.3 ^-0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.2 ^-0.1 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.6 ^-0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.3 ^-0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0 ^-0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.1 ^-0.2 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.5 ^-0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.4 ^-0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.2 ^-0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.1 ^-0.3 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.6 ^-0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.3 ^-0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0 ^-0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.1 ^-0.4 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.7 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.5 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.4 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.2 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.1 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.2 ^-0.5 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.7 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.5 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.4 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.2 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.1 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.2 ^-0.6 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-1 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.9 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.8 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.7 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.6 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.1 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^0.2 ^-0.7 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-1 ^-0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.9 ^-0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.7 ^-0.8 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-1 ^-0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.9 ^-0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.8 ^-0.9 ^0 0 0 0 0 1 force @a
particle dust{color:[1.000,0.843,0.000],scale:0.8} ^-0.7 ^-0.9 ^0 0 0 0 0 1 force @a
